### ISSUE TITLE
event and info/participation/result tab interfere

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#1208] opened 2018-04-24 13:07 UTC
If I click on an event in the timeline first and then activate the result, info or participation tab, the content of the event description stays visible and the info/participation/result tab content is not displayed or not correctly displayed. 

Tested on Safari 10.13.3 and Firefox 59.0.2
Can be tested here: https://opin-stage.liqd.net/de/projects/liquid-zukunftstage-2018-themen/
![bildschirmfoto 2018-04-24 um 15 06 36](https://user-images.githubusercontent.com/15341015/39188882-2ad0210e-47d1-11e8-953a-c0378f5a4eca.png)

**Comment by gereonrahnfeld** [comment] 2018-04-24 14:00
see also issue #1162

**Comment by rmader** [comment] 2020-04-16 08:27
Duplicate of #1162

**Closed by rmader** 2020-04-16 08:27 UTC
Labels: Type: Bug
