### ISSUE TITLE
Data from results tab and participation tab are shown at the same time

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1162] opened 2018-03-21 16:21 UTC
I found a weird error: when I set up a project and than go to preview it looks alright. However, when I then go to an offline event (which was set to a time that has already passed by 2 hours) and then click to the information tab and then to the results tab and then again to the participation tab: I see the data from the participation tab (description of offline event) and data from the result tab at the same time. 

![screen shot 2018-03-21 at 17 16 25](https://user-images.githubusercontent.com/15954895/37722431-4c58b300-2d2c-11e8-8140-e825f8a80a34.png)

![screen shot 2018-03-21 at 17 16 41](https://user-images.githubusercontent.com/15954895/37722441-50f39f74-2d2c-11e8-9375-88fc12327391.png)

![screen shot 2018-03-21 at 17 16 55](https://user-images.githubusercontent.com/15954895/37722451-55db8b78-2d2c-11e8-921d-8dfcaf0c6a41.png)

**Comment by fuzzylogic2000** [comment] 2022-03-10 09:59
@hello-kathi What about this one? Could you reproduce it?

**Comment by hello-kathi** [comment] 2022-03-10 10:27
@fuzzylogic2000 OMG Yes I just did it, that is really weird!

**Comment by fuzzylogic2000** [comment] 2022-03-10 10:31
@phillimorland Could this be because of some html tags not opening or closing properly? Or do you have any idea what else it could be?

**Comment by phillimorland** [comment] 2022-03-10 10:40
will take a look

**Closed** 2022-03-11 08:39 UTC
Labels: Type: Bug, Prio: Medium
