### ISSUE TITLE
Escaped charachters in blog feed

### ISSUE THREAD

**Issue by ihucos** [liqd/a4-opin#1216] opened 2018-05-07 10:22 UTC
I could not find it in production, on dev there are unescaped special html charachters:
![screenshot from 2018-05-03 18-34-32](https://user-images.githubusercontent.com/2066372/39697240-895e3e26-51f0-11e8-97cf-00b29464de26.png)

One fix would be easy:
Don't escape the description from the RSS feed:
https://github.com/liqd/a4-opin/blob/master/euth_wagtail/templates/includes/rss_import.html#L8

buuut..
That would mean we have to "trust" the feed, which is an external site to not have any HTML injection.
Possibly we could also selectively just escape the characters by using the removtags filter before unescaping... but in the end, here is the issue but not a PR since I did not see that in production.

**Comment by MagdaN** [comment] 2018-05-07 11:01
The rss import is not used anymore, so we could remove the feature completely

**Comment by ihucos** [comment] 2018-05-07 11:06
Yes, so I guess this issue would be about fixing this by removing the feature

**Comment by rmader** [comment] 2020-04-16 08:31
Duplicate of #1019

**Closed by rmader** 2020-04-16 08:31 UTC
