### ISSUE TITLE
Denglisch in notification emails

### ISSUE THREAD

**Issue by rittermo** [liqd/a4-opin#903] opened 2017-08-03 08:34 UTC
My notitification email (from opin-stage) has a strange mix of german object and English text.

![bildschirmfoto 2017-08-03 um 10 33 49](https://user-images.githubusercontent.com/15341015/28913161-5a3e1a6e-7837-11e7-908c-931a91121983.png)

**Comment by slomo** [comment] 2017-09-01 08:57
Fixed in adhocracy4, probably we are on an old version.

**Comment by slomo** [comment] 2017-09-01 08:59
Duplicate of #877

**Closed by slomo** 2017-09-01 08:59 UTC
