### ISSUE TITLE
Richtext video embed styling - iframe very small 

### ISSUE THREAD

**Issue by hello-kathi** [liqd/a4-opin#2344] opened 2021-09-21 07:30 UTC
**URL:** OPIN.me
**user:** Admin
**expected behaviour:** I insert the youtube link onto the video block or the richtext editor and the video is shown in a proper size
**behaviour:** Issue warning that the link is invalid
**important screensize:**
**device & browser:** 
**Comment/Question:** 
There is another behaviour on OPIN dev:
The Video Block is working super fine now, but in the richtext editor the video appears very small, but it is possible to insert the youtube link and save it.

Question: Do we have to fix it on Prod, if the have to do it on Dev and then deploy anyway on prod?

Screenshot
<img width="994" alt="Bildschirmfoto 2021-09-21 um 09 24 23" src="https://user-images.githubusercontent.com/52459078/134129355-5c321cf4-991c-4c6e-b5e9-c55453518c3b.png">
?

**Comment by phillimorland** [comment] 2021-09-22 12:50
@hello-kathi So this issue is a little confusing so just to clarify one point about dev, stage and prod: 
If you find an issue on prod which is not on dev, that means that hopefully the issue will be resolved in the next release, there is the odd occasion where an issue on prod is a result of the server settings and config and thats why we do stage releases and testing. The stage server is an identicle environment to prod and so stage releases are mostly to check if there are any issues that are caused by having a different server from dev. Hope that helps with prod dev thing?  
Ok so I think this issue is actually a styling issue for dev, is that correct? and if so can you add a url?

**Comment by hello-kathi** [comment] 2021-09-22 13:44
@phillimorland That is correct! Ok and sorry for the Confusion!
https://opin-dev.liqd.net/de/best-practices/from-youth-horizont-in-georgia/
On this page if you scroll to the end I put in a rich text block and inserted a video Link and underneath I inserted a video block (that is working fine now!) You will see that the the Youtube Video in the Richtext Block is very small.

**Comment by phillimorland** [comment] 2021-09-22 14:46
@hello-kathi cool, thanks for clarification! :)
and one more clarification, as there is a working way to add videos that is correctly styled, this is not a release issue, is that correct?

**Comment by hello-kathi** [comment] 2021-09-22 14:53
@phillimorland trick question ;) No, if the Video Block is working after release (and it should because it is working on dev), then we can do this in the next weeks and I can do a workaround with the Video Block.

**Closed** 2021-09-27 13:44 UTC
Labels: Dev: Styling
