### ISSUE TITLE
add translations of notifications

### ISSUE THREAD

**Issue by gereonrahnfeld** [liqd/a4-opin#1429] opened 2019-03-05 09:02 UTC
apparently there are no translations of the different notifications.

**Comment by rmader** [comment] 2020-04-15 15:00
This sound like we need per user language settings like in A+ - otherwise there's no way for the backend to tell what language it should choose.

**Comment by rmader** [comment] 2020-04-15 15:32
Duplicate of #712

**Closed by rmader** 2020-04-15 15:32 UTC
